### ISSUE TITLE
Kaizoyu for android tv 

### ISSUE THREAD

**Issue by Dantesinferno11** [astarivi/Kaizoyu#5]
I love the app and i think would be Good idea if a Android tv version it's created. Thanks you dev

**Comment by GoluLiliput** [comment]
Same...

**Comment by astarivi** [comment]
An Android TV version is planned, and I would probably start working it after release 1.0 of the app. 

As I can only focus in one version at a time, I'm trying to build a good base Android version first, before shifting attention to TV version.

Will be marking this issue closed as #2 will be used as the main issue to discuss Android TV. Thanks for the feedback.
