### ISSUE TITLE
Add Toolbar to Settings and Storage activities

### ISSUE THREAD

**Issue by astarivi** [astarivi/Kaizoyu#8]
For feature parity with the Library categories, a top toolbar should be added to Settings and Storage activities, just like the one used in the Library activities.

Relevant code:

- [Library Activity Toolbar layout](https://github.com/astarivi/Kaizoyu/blob/c5d106313bd3b96b83ee7f80aefb93cb78e6b28b/app/src/main/res/layout/activity_shared_library.xml#L63)
- [Settings Activity layout](https://github.com/astarivi/Kaizoyu/blob/main/app/src/main/res/layout/activity_settings.xml)
- [Storage Activity layout](https://github.com/astarivi/Kaizoyu/blob/main/app/src/main/res/layout/activity_storage.xml)
- [Settings Activity class](https://github.com/astarivi/Kaizoyu/blob/main/app/src/main/java/com/astarivi/kaizoyu/gui/more/settings/SettingsActivity.java)
- [Storage Activity class](https://github.com/astarivi/Kaizoyu/blob/main/app/src/main/java/com/astarivi/kaizoyu/gui/more/storage/StorageActivity.java)

**Comment by Zaid-0504** [comment]
Hey @astarivi can you assign me this issue. I am willing to work in this one.

**Comment by astarivi** [comment]
@Zaid-0504 Sure thing. If you have any further questions about the issue, or anything related, feel free to DM me in discord, nickname is "astarivi".

**Comment by Zaid-0504** [comment]
@astarivi there are some undefined string res declared in the code pls take a look into those
